speedml::feature::Feature
tuple speedml.feature.Feature::__combine__
def speedml.feature.Feature.drop
Drop one or more list of strings naming ``features`` from train and test datasets.
def speedml.feature.Feature.impute
Replace empty values in the entire dataframe with median value for numerical features and most common values for text features.
References speedml.feature.Feature.sum.
def speedml.feature.Feature.mapping
Convert values for categorical feature ``a`` using ``data`` dictionary. Use when number of categories are limited otherwise use labels.
def speedml.feature.Feature.fillna
Fills empty or null values in ``a`` feature name with ``new`` string value.
References speedml.feature.Feature.sum.
def speedml.feature.Feature.replace
In feature ``a`` values ``match`` string or list of strings and replace with a ``new`` string.
Referenced by speedml.feature.Feature.divide.
def speedml.feature.Feature.outliers
Fix outliers for ``lower`` or ``upper`` or both percentile of values within ``a`` feature.
def speedml.feature.Feature.density
Create new feature named ``a`` feature name + suffix '_density', based on density or value_counts for each unique value in ``a`` feature specified as a string or multiple features as a list of strings.
References speedml.feature.Feature._density_by_feature.
def speedml.feature.Feature.add
Update ``a`` numeric feature by adding ``num`` number to each values.
def speedml.feature.Feature.sum
Create ``new`` numeric feature by adding ``a`` + ``b`` feature values.
Referenced by speedml.feature.Feature.fillna, speedml.feature.Feature.impute.
def speedml.feature.Feature.diff
Create ``new`` numeric feature by subtracting ``a`` - ``b`` feature values.
def speedml.feature.Feature.product
Create ``new`` numeric feature by multiplying ``a`` * ``b`` feature values.
def speedml.feature.Feature.divide
Create ``new`` numeric feature by dividing ``a`` / ``b`` feature values. Replace division-by-zero with zero values.
References speedml.feature.Feature.replace.
def speedml.feature.Feature.round
Create ``new`` numeric feature by rounding ``a`` feature value to ``precision`` decimal places.
def speedml.feature.Feature.concat
Create ``new`` text feature by concatenating ``a`` and ``b`` text feature values, using ``sep`` separator.
def speedml.feature.Feature.list_len
Create ``new`` numeric feature based on length or item count from ``a`` feature containing list object as values.
def speedml.feature.Feature.word_count
Create ``new`` numeric feature based on length or word count from ``a`` feature containing free-form text.
def speedml.feature.Feature.extract
Match ``regex`` regular expression with ``a`` text feature values to update ``a`` feature with matching text if ``new`` = None. Otherwise create ``new`` feature based on matching text.
References speedml.feature.Feature._regex_text.
def speedml.feature.Feature.labels
Generate numerical labels replacing text values from list of categorical ``features``.
References speedml.feature.Feature.cut.
def speedml.feature.Feature.cut
Return indices of half-open bins to which each value of `x` belongs. Parameters ---------- refFeature: the feature which will be cutted newFeature: new name of the feature which is the result of pd.cut bins : int, sequence of scalars, or IntervalIndex If `bins` is an int, it defines the number of equal-width bins in the range of `x`. However, in this case, the range of `x` is extended by .1% on each side to include the min or max values of `x`. If `bins` is a sequence it defines the bin edges allowing for non-uniform bin width. No extension of the range of `x` is done in this case. right : bool, optional Indicates whether the bins include the rightmost edge or not. If right == True (the default), then the bins [1,2,3,4] indicate (1,2], (2,3], (3,4]. labels : array or boolean, default None Used as labels for the resulting bins. Must be of the same length as the resulting bins. If False, return only integer indicators of the bins. retbins : bool, optional Whether to return the bins or not. Can be useful if bins is given as a scalar. precision : int, optional The precision at which to store and display the bins labels include_lowest : bool, optional Whether the first interval should be left-inclusive or not. Returns ------- out : Categorical or Series or array of integers if labels is False The return type (Categorical or Series) depends on the input: a Series of type category if input is a Series else Categorical. Bins are represented as categories when categorical data is returned. bins : ndarray of floats Returned only if `retbins` is True. Notes ----- The `cut` function can be useful for going from a continuous variable to a categorical variable. For example, `cut` could convert ages to groups of age ranges. Any NA values will be NA in the result. Out of bounds values will be NA in the resulting Categorical object Examples -------- >>> pd.cut(np.array([.2, 1.4, 2.5, 6.2, 9.7, 2.1]), 3, retbins=True) ... # doctest: +ELLIPSIS ([(0.19, 3.367], (0.19, 3.367], (0.19, 3.367], (3.367, 6.533], ... Categories (3, interval[float64]): [(0.19, 3.367] < (3.367, 6.533] ... >>> pd.cut(np.array([.2, 1.4, 2.5, 6.2, 9.7, 2.1]), ... 3, labels=["good", "medium", "bad"]) ... # doctest: +SKIP [good, good, good, medium, bad, good] Categories (3, object): [good < medium < bad] >>> pd.cut(np.ones(5), 4, labels=False) array([1, 1, 1, 1, 1])
Referenced by speedml.feature.Feature.labels.
def speedml.feature.Feature.mapFunction
References speedml.feature.Feature.get_dummies.
def speedml.feature.Feature.get_dummies
Referenced by speedml.feature.Feature.mapFunction.
def speedml.feature.Feature._density_by_feature
Referenced by speedml.feature.Feature.density.
def speedml.feature.Feature._regex_text
Referenced by speedml.feature.Feature.extract.