speedml::tuning
tuple speedml::tuning.lgb
def speedml.tuning.method_name
def speedml.tuning.logger_set
创建一个logger :rtype : loger
Referenced by speedml.tuning.auto_tuning.
def speedml.tuning.calculater
Referenced by speedml.tuning.auto_tuning.
def speedml.tuning.createSamples
References speedml.tuning.get_decimal_place, speedml.tuning.intRange.
Referenced by speedml.tuning.auto_tuning.
def speedml.tuning.intRange
Referenced by speedml.tuning.createSamples.
def speedml.tuning.is_converge
References speedml.tuning.combine_dict, speedml.tuning.expand_both.
Referenced by speedml.tuning.auto_tuning.
def speedml.tuning.expand_both
Referenced by speedml.tuning.is_converge.
def speedml.tuning.combine_dict
Referenced by speedml.tuning.is_converge.
def speedml.tuning.get_decimal_place
Referenced by speedml.tuning.auto_tuning, speedml.tuning.createSamples.
def speedml.tuning.auto_tuning
params包含参数的字典，每个参数的值由四维tuple构成，前两位是初始最小、最大，后两位是取值上下极限边界,若上下极限边界值为-1表示不做上下极限限制 如：learning_rate:(0.05,0.3,0,1)表示learning_rate初始范围为（0.05,0.3），当在给范围找不到最优结果时，会扩大到（0,1）内 注意：模型参数要么在0-1间，要么在1-无穷，其中1-无穷的参数，自动生成的参数均为整数 :param model: 模型 :param init_param:模型的初始值 :param params: 参数寻优范围列表 :param data: 训练数据 :param target:训练数据中的目标 :param expand:当初始寻优范围内寻优失败时，扩大边界所乘或除的系数，下边界除以expand，上边界乘expand :param samples: 每次迭代寻优时，参数点数 :return:训练好的模型
References speedml.tuning.calculater, speedml.tuning.createSamples, speedml.tuning.get_decimal_place, speedml.tuning.is_converge, speedml.tuning.logger_set.