speedml::plot::Plot
def speedml.plot.Plot.crosstab
Return a dataframe cross-tabulating values from feature ``x`` and ``y``.
def speedml.plot.Plot.bar
Bar plot ``x`` across ``y`` feature values.
def speedml.plot.Plot.strip
Stripplot plot ``x`` across ``y`` feature values.
def speedml.plot.Plot.distribute
Plot multiple feature distribution histogram plots for all numeric features. This helps understand skew of distribution from normal to quickly and relatively identify outliers in the dataset.
def speedml.plot.Plot.correlate
Plot correlation matrix heatmap for numerical features of the training dataset. Use this plot to understand if certain features are duplicate, are of low importance, or possibly high importance for our model.
def speedml.plot.Plot.ordinal
Plot ordinal features (categorical numeric) using Violin plot against target feature. Use this to determine outliers within ordinal features spread across associated target feature values.
def speedml.plot.Plot.continuous
Plot continuous features (numeric) using scatter plot. Use this to determine outliers within continuous features.
def speedml.plot.Plot.model_ranks
Plot ranking among accuracy offered by various models based on our datasets.
def speedml.plot.Plot.importance
Plot importance of features based on ExtraTreesClassifier.
References speedml.plot.Plot._plot_importance.
def speedml.plot.Plot.xgb_importance
Plot importance of features based on XGBoost.
References speedml.plot.Plot._create_feature_map, speedml.plot.Plot._plot_importance.
def speedml.plot.Plot._create_feature_map
Referenced by speedml.plot.Plot.xgb_importance.
def speedml.plot.Plot._plot_importance
Referenced by speedml.plot.Plot.importance, speedml.plot.Plot.xgb_importance.