module2
string module2.__author__
tuple module2.sml
module2.train
module2.test
list module2.ntrain
list module2.ntest
tuple module2.data
list module2.match
string module2.new
module2.y_train
tuple module2.train_avg
module2.test_avg
tuple module2.param_test3
module2.estimator
dictionary module2::init_param
tuple module2.param_test5
tuple module2.xgb
def module2.logger_set
创建一个logger :rtype : loger
Referenced by auto_tuning.
def module2.calculater
Referenced by auto_tuning.
def module2.createSamples
References intRange.
Referenced by auto_tuning.
def module2.intRange
Referenced by createSamples.
def module2.is_converge
References combine_dict, expand_both.
Referenced by auto_tuning.
def module2.expand_both
Referenced by is_converge.
def module2.combine_dict
Referenced by is_converge.
def module2.auto_tuning
params包含参数的字典，每个参数的值由四维tuple构成，前两位是初始最小、最大，后两位是取值上下极限边界,若上下极限边界值为-1表示不做上下极限限制 如：learning_rate:(0.05,0.3,0,1)表示learning_rate初始范围为（0.05,0.3），当在给范围找不到最优结果时，会扩大到（0,1）内 :param model: 模型 :param init_param:模型的初始值 :param params: 参数寻优范围列表 :param data: 训练数据 :param target:训练数据中的目标 :param expand:当初始寻优范围内寻优失败时，扩大边界所乘或除的系数，下边界除以expand，上边界乘expand :param samples: 每次迭代寻优时，参数点数 :return:训练好的模型
References calculater, createSamples, is_converge, logger_set.
def module2.ignore_warn